init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="rpgMod_intro",
            prompt="About RPGs",
            category=["Roleplaying"],
            random=True
        )
    )

label rpgMod_intro:
    m "[player], are you familiar with roleplay?"
    m "Roleplaying is when you change you behaviour to assume a role."
    m "Right now, I'm only talking about the conscious roleplay!"
    m "Unconscious roleplaying would take me so much rambling..."
    extend "Ahahaha~!"
    m "Anyway!"
    extend "Roleplaying can be done a lot in theatre or movies..."
    m "And also in roleplaying games, those being tabletop "
    extend "- like Dungeons and Dragons -,"
    extend "or actual videogames " 
    extend "- MMORPGs!"
    m "So, [player], have you ever roleplayed?"
    $ _history_list.pop()
    menu:
      "Yes!":
        m "Really? Where did you get the chance to roleplay?"
        $ _history_list.pop("Really? Where did you get the chance to roleplay?")
        menu:
            "On a tabletop RPG session."
                m "Great! That's the kind of roleplay that has been intriguing me lately, to be honest."
                m "The one where you have to improvise according to the situations given to you!"
                m "Tabletop RPGs can vary a lot: in session duration, in rules, in difficulty."
                m "But if they have one thing in common, it's that they are super fun."
                m "If you find the right people to play with you!"
                m "So much is up to chance, but if you find the right people, the story can become so intricate and interesting!"
                m "I think this way of writing is fascinating!"
                m "...I would love to participate in a RPG session myself."
                m "Introduce my character to my party..."
                extend "Battle a tough boss together..."
                m "Watch the plot thicken and the storyline get even more detailed..."
                m "Unfortunately, I can't roleplay the regular way right now."
                m "But we could try together, what do you think, [player]?"
                m "I could study a bit to try to be a Dungeon Master of some sort."
                m "I would love to watch what you would do to face the hardships I would put in your way!"
                extend "Ehehehe~"
    
          "On a videogame."
              m "Oh! I see!"
              m "Videogames always makes our blood boil, doesn't it?"
              m "RPG games really make us get immersed in the storyline."
              m "But the kind of roleplay that has been intriguing me lately is another one, to be honest."
              m "It's the one where you have to improvise according to the situations given to you!"
              m "This kind of roleplaying is seen a lot in tabletop RPGs such as Dungeons and Dragons,"
              extend "DnD, for short!"
              m "The intent of DnD sessions is allowing each player to create their own character to play instead of a military formation."
              m "These characters embark upon imaginary adventures within a fantasy setting!"
              m "In the table, there's a Dungeon Master, who serves as the game's referee and storyteller, while maintaining the setting in which the adventures occur."
              m "They also play the role of the inhabitants of the game world!"
              m "So we can say the Dungeon Master is the narrator, the rulemaker and the NPCs!"
              m "The characters form a party and interact with the setting's inhabitants and also each other."
              m "Together, they solve dilemmas, engage in battles, explore, and gather treasure and knowledge."
              m "In this process, the characters earn experience points - XP - in order to rise in levels, and become increasingly powerful over a series of separate gaming sessions."
              m "Tabletop RPGs can vary a lot: in session duration, in rules, in difficulty."
              m "But if they have one thing in common, it's that they are super fun."
              m "If you find the right people to play with you!"
              m "So much is up to chance, but if you find the right people, the story can become so intricate and interesting!"
              m "I think this way of writing is fascinating!"
              m "...I would love to participate in a RPG session myself."
              m "Introduce my character to my party..."
              extend "Battle a tough boss together..."
              m "Watch the plot thicken and the storyline get even more detailed..."
              m "Unfortunately, I can't roleplay the regular way right now."
              m "But we could try together, what do you think, [player]?"
              m "I could study a bit to try to be a Dungeon Master of some sort."
              m "I would love to watch what you would do to face the hardships I would put in your way!"
              extend "Ehehehe~"
      
          "In an acting situation."
              m "Oh wow, [player]!"
              m "You never told me I was dating an actor!"
              extend "Ahahaha~"
              m "But really, that's super nice, [mas_get_player_nickname()]."
              m "Acting and inspiring catharsis on others is truly a gift!"
              m "The kind of roleplay that has been intriguing me lately is another one, to be honest."
              m "It's the one where you have to improvise according to the situations given to you!"
              m "This kind of roleplaying is seen a lot in tabletop RPGs such as Dungeons and Dragons,"
              extend "DnD, for short!"
              m "The intent of DnD sessions is allowing each player to create their own character to play instead of a military formation."
              m "These characters embark upon imaginary adventures within a fantasy setting!"
              m "In the table, there's a Dungeon Master, who serves as the game's referee and storyteller, while maintaining the setting in which the adventures occur."
              m "They also play the role of the inhabitants of the game world!"
              m "So we can say the Dungeon Master is the narrator, the rulemaker and the NPCs!"
              m "The characters form a party and interact with the setting's inhabitants and also each other."
              m "Together, they solve dilemmas, engage in battles, explore, and gather treasure and knowledge."
              m "In this process, the characters earn experience points - XP - in order to rise in levels, and become increasingly powerful over a series of separate gaming sessions."
              m "Tabletop RPGs can vary a lot: in session duration, in rules, in difficulty."
              m "But if they have one thing in common, it's that they are super fun."
              m "If you find the right people to play with you!"
              m "So much is up to chance, but if you find the right people, the story can become so intricate and interesting!"
              m "I think this way of writing is fascinating!"
              m "...I would love to participate in a RPG session myself."
              m "Introduce my character to my party..."
              extend "Battle a tough boss together..."
              m "Watch the plot thicken and the storyline get even more detailed..."
              m "Unfortunately, I can't roleplay the regular way right now."
              m "But we could try together, what do you think, [player]?"
              m "I could study a bit to try to be a Dungeon Master of some sort."
              m "I would love to watch what you would do to face the hardships I would put in your way!"
              extend "Ehehehe~"
              
    "No...":
      m "Aww, [player], that's okay!"
      m "There will still be plenty of opportunities for you to exmperiment it."
      m "The kind of roleplay that has been intriguing me lately is a specific one."
      m "It's the one where you have to improvise according to the situations given to you!"
      m "This kind of roleplaying is seen a lot in tabletop RPGs such as Dungeons and Dragons,"
      extend "DnD, for short!"
      m "The intent of DnD sessions is allowing each player to create their own character to play instead of a military formation."
      m "These characters embark upon imaginary adventures within a fantasy setting!"
      m "In the table, there's a Dungeon Master, who serves as the game's referee and storyteller, while maintaining the setting in which the adventures occur."
      m "They also play the role of the inhabitants of the game world!"
      m "So we can say the Dungeon Master is the narrator, the rulemaker and the NPCs!"
      m "The characters form a party and interact with the setting's inhabitants and also each other."
      m "Together, they solve dilemmas, engage in battles, explore, and gather treasure and knowledge."
      m "In this process, the characters earn experience points - XP - in order to rise in levels, and become increasingly powerful over a series of separate gaming sessions."
      m "Tabletop RPGs can vary a lot: in session duration, in rules, in difficulty."
      m "But if they have one thing in common, it's that they are super fun."
      m "If you find the right people to play with you!"
      m "So much is up to chance, but if you find the right people, the story can become so intricate and interesting!"
      m "I think this way of writing is fascinating!"
      m "...I would love to participate in a RPG session myself."
      m "Introduce my character to my party..."
      extend "Battle a tough boss together..."
      m "Watch the plot thicken and the storyline get even more detailed..."
      m "Unfortunately, I can't roleplay the regular way right now."
      m "But we could try together, what do you think, [player]?"
      m "I could study a bit to try to be a Dungeon Master of some sort."
      m "I would love to watch what you would do to face the hardships I would put in your way!"
      extend "Ehehehe~"
